os: osx
osx_image: xcode11

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Cellar/emacs-plus

addons:
  homebrew:
    update: true
    packages:
    - emacs-plus

# The install script should be idempotent, so run it twice
install:
  - ./install.sh
  - ./install.sh

before_script:
  - source env.sh

script: make test

before_cache:
  - brew cleanup