(source gnu)
(source melpa)

(package "calctex" "0.1" "WYSIWYG LaTeX equation editing with calc.el")
(files "calctex.el"
       "org-calctex.el"
       "calctex-contrib.el"
       ("vendor" ("texd" "vendor/texd/bin/dvichop" "vendor/texd/dvichop.sty")))

(depends-on "posframe")
(depends-on "hydra")
(depends-on "cdlatex")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
