(source gnu)
(source melpa)

(package "org-calctex" "0.1" "WYSIWYG LaTeX equation editing with calc.el")
(files "org-calctex.el")

(depends-on "posframe")
(depends-on "hydra")
(depends-on "cdlatex")
(depends-on "calctex")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
