(source gnu)
(source melpa)

(package "calctex" "0.1" "WYSIWYG LaTeX equation editing with calc.el")
(files "calctex.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
